condition ex

diff --git a/script-ex12 b/script-ex12
--- a/script-ex12
+++ b/script-ex12
@@ -1,9 +1,11 @@
 #!/bin/bash
 
-Userid=$(id -u)
- echo "user id is: $Userid"
+#Functions and enabling colors for failed and success Script
 
-R="\e[31m"
+Userid=$(id -u)
+  echo "userid is : $Userid"
+
+R="\e[31m"  #colors syntax
 G="\e[32m"
 Y="\e[33m"
 N="\e[0m"
@@ -11,22 +13,22 @@ N="\e[0m"
 CHECK_ROOT(){
     if [ $Userid -ne 0 ]
     then
-       echo "please login with root previleges"
+       echo "User should have root previleges"
        exit 1
-    fi   
+    fi
 }
 
 VALIDATE(){
     if [ $1 -ne 0 ]
     then
-        echo -e "$2 is ... $R Failed $N"
-        exit 1
+      echo -e "$2 is.. $R Failed $N"
+      exit 1
     else
-        echo -e "$2 is ... $G Success $N"
-    fi        
+      echo -e "$2 is.. $G Success $N"
+    fi  
 }
 
-CHECK_ROOT()
+CHECK_ROOT
 
 for package in $@
 do
